name: CI

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-26]
    steps:
      - uses: actions/checkout@v6

      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: cachix/cachix-action@v16
        with:
          name: igm
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Install devenv
        run: nix profile install nixpkgs#devenv

      - run: devenv test
      - run: nix flake check
      - run: nix build .#all
