name: CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, macos-latest, macos-15-intel]
    steps:
      - uses: actions/checkout@v6

      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v16
        with:
          name: igm
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - run: nix flake check --print-build-logs
      - name: Build devShell
        run: nix develop --print-build-logs --command true
