name: CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, macos-latest, macos-15-intel]
    steps:
      - uses: actions/checkout@v6

      - uses: DeterminateSystems/determinate-nix-action@v3
        if: runner.os != 'macOS' || runner.arch != 'X64'
      - uses: DeterminateSystems/flakehub-cache-action@main
        if: runner.os != 'macOS' || runner.arch != 'X64'

      - uses: cachix/install-nix-action@v31
        if: runner.os == 'macOS' && runner.arch == 'X64'
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: cachix/cachix-action@v16
        with:
          name: igm
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Install devenv
        run: nix profile install nixpkgs#devenv

      - run: devenv test
      - run: nix flake check --print-build-logs
